export PATH="/opt/homebrew/bin:$PATH"

source $(brew --prefix)/opt/zinit/zinit.zsh
. $(brew --prefix asdf)/libexec/asdf.sh

zinit light zsh-users/zsh-completions

autoload compinit
compinit

zinit light zsh-users/zsh-autosuggestions
zinit light zdharma-continuum/fast-syntax-highlighting

unsetopt inc_append_history
unsetopt share_history

export CLICOLOR=1;

precmd () {print -Pn "\e]0;%~\a"}

alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
alias vim=nvim
alias k=kubectl
alias kns=k9s
alias tf=terraform
alias ls=exa

source <(kubectl completion zsh)

eval "$(starship init zsh)"
