export PATH="/opt/homebrew/bin:$PATH"

source $(brew --prefix)/opt/zinit/zinit.zsh
. $(brew --prefix asdf)/libexec/asdf.sh

# bindkey -v

zinit load zdharma-continuum/history-search-multi-word

autoload compinit
compinit

zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|=*' 'l:|=* r:|=*'
fpath=(/usr/local/share/zsh-completions $fpath)

zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light zdharma-continuum/fast-syntax-highlighting

HISTFILE=$HOME/.zsh_history
HISTSIZE=1000
SAVEHIST=1000
setopt inc_append_history
setopt share_history
setopt hist_expire_dups_first
setopt hist_ignore_dups
setopt hist_reduce_blanks
setopt extended_history

export CLICOLOR=1;

precmd () {print -Pn "\e]0;%~\a"}

alias tailscale="/Applications/Tailscale.app/Contents/MacOS/Tailscale"
alias vim=nvim
alias k=kubectl
alias kns=k9s
alias tf=terraform
alias ls=exa
alias p=pnpm
alias n=npm

source <(kubectl completion zsh)

export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"

eval "$(starship init zsh)"
